---

- name: Check OS versions
  ansible.builtin.include_tasks: epel.yml
  when:
    - (ansible_facts['distribution'] == "Amazon" and
      ansible_facts['distribution_major_version'] == "2") or
      (ansible_facts['distribution'] in ["RedHat", "CentOS", "Rocky", "AlmaLinux"])
