---

- include_tasks: epel.yml
  when:
    - (ansible_distribution == "Amazon" and
      ansible_distribution_major_version == "2") or
      (ansible_distribution in [ "RedHat", "CentOS", "Rocky", "AlmaLinux" ])
