---
molecule_exceptions:
  - variation: "Ubuntu*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "Debian*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "Fedora*"
    reason: "repo only supports RedHat/CentOS Server"
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current", "development"]
    platforms:
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "ubi8"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
