---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    molecule_repo_file: "epel.repo"
    molecule_repo_name: "epel"
    molecule_repo_package:
      RedHat:
        "7":
          - "zork"
        "8":
          - "zork"
      CentOS:
        "7":
          - "zork"
        "8":
          - "zork"
        "9":
          - "zerofree"
      Rocky:
        "8":
          - "zork"
      AlmaLinux:
        "8":
          - "zork"
      Amazon:
        "2":
          - "zork"

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Test if repository exists and is enabled
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ molecule_repo_file }}"
        section: "{{ molecule_repo_name }}"
        option: enabled
        value: "1"
        no_extra_spaces: true
        mode: "0644"
      register: molecule_repository
      failed_when: (molecule_repository is changed) or (molecule_repository is failed)

    - name: Check package is installable from repository
      ansible.builtin.yum:
        name: "{{ molecule_repo_package[ansible_distribution][ansible_distribution_major_version] }}"
        state: present
      register: package_installed
